ERROR output added

diff --git a/archive_it b/archive_it
--- a/archive_it
+++ b/archive_it
@@ -38,6 +38,10 @@ archive() {
   BACKUPDATE=`cat /tmp/.git_restore_test | head -1`
   NOW=`date +%s`
   AGE=`echo $NOW - $BACKUPDATE | bc`
+  if [ "$AGE" -lt 0 -o "$AGE" -gt 7200 ]; then
+    echo "ERROR in $0 on `hostname` archiving `pwd`"
+    echo "ERROR in $0 on `hostname` archiving `pwd`" >&2
+  fi
   echo AGE=$AGE
 }
 
